#  To remove!
#  docker compose --file compose.yaml down && docker volume rm chroma-data
services:
  server:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - "8000:8000"
    networks:
      - net

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - net

volumes:
  chroma-data:
    driver: local

networks:
  net:
    driver: bridge