services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=chats'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=nathan'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '64034:5432'