services:
  server:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - "8000:8000"
    networks:
      - net

volumes:
  chroma-data:
    driver: local

networks:
  net:
    driver: bridge